services:
  dev:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        DEV_USERNAME: ${DEV_USERNAME}
        DEV_UID: ${DEV_UID}
        DEV_GID: ${DEV_GID}
        PYTHON_VERSION: ${PYTHON_VERSION}
        NODE_MAJOR: ${NODE_MAJOR}
        MAVEN_VERSION: ${MAVEN_VERSION}
        GRADLE_VERSION: ${GRADLE_VERSION}
        SPRINGBOOT_CLI_VERSION: ${SPRINGBOOT_CLI_VERSION}
        TZ: ${TZ}
    container_name: dev-intellij-box
    env_file: [.env]
    user: "${DEV_UID}:${DEV_GID}"
    working_dir: /workspace
    environment:
      # Provide generic names your app can read, alongside Spring overrides
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_URL_JDBC: ${DATABASE_URL_JDBC}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./:/workspace
      - home:/home/${DEV_USERNAME}
      - pyenv:/opt/pyenv
      - npm:/home/${DEV_USERNAME}/.npm
      - m2:/home/${DEV_USERNAME}/.m2
      - gradle:/home/${DEV_USERNAME}/.gradle
      - ./secrets/ssh/authorized_keys.list:/etc/ssh/authorized_keys.list:ro
    ports:
      - "${SSH_PORT}:22"
      - "${APP_PORT}:8080"
      - "${UI_PORT}:5173"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

volumes:
  home:
  pyenv:
  npm:
  m2:
  gradle:
